# Generated by Django 3.1.4 on 2021-01-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamreader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamreader',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dreamreader',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
