# Generated by Django 3.1.4 on 2022-07-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipflow', '0002_auto_20220715_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('access_key', models.CharField(blank=True, max_length=255, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('console_url', models.CharField(blank=True, max_length=4096, null=True)),
            ],
        ),
    ]
