# Generated by Django 3.1.4 on 2022-07-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipflow', '0004_auto_20220726_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowlog',
            name='bytes_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flowlog',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
