# Generated by Django 3.1.4 on 2022-07-28 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipflow', '0005_auto_20220727_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipflow.flowlog')),
            ],
        ),
    ]
