# Generated by Django 3.1.4 on 2022-07-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipflow', '0006_s3object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowlog',
            name='bytes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowlog',
            name='bytes_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowlog',
            name='dstport',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowlog',
            name='end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowlog',
            name='packets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowlog',
            name='protocol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowlog',
            name='srcport',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowlog',
            name='start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
