# Generated by Django 3.1.4 on 2022-07-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipflow', '0008_auto_20220731_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowlog',
            name='bytes_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
