# Generated by Django 2.2.8 on 2020-12-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_lead', '0002_auto_20201204_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='blub',
            field=models.TextField(blank=True, null=True),
        ),
    ]
