# Generated by Django 3.1.4 on 2021-02-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3_uploader', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
