# Generated by Django 3.1.4 on 2021-01-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3_uploader', '0003_roominfo_roomvisitors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomvisitors',
            old_name='room_id',
            new_name='room',
        ),
    ]
