# Generated by Django 3.1.4 on 2021-01-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3_uploader', '0005_auto_20210117_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominfo',
            name='room_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
