# Generated by Django 3.1.4 on 2021-01-30 11:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('s3_uploader', '0006_auto_20210121_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomRecording',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recording_link', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s3_uploader.roominfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
