# Generated by Django 3.1.4 on 2021-02-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3_uploader', '0007_roomrecording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomrecording',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomvisitors',
            name='room',
        ),
        migrations.DeleteModel(
            name='RoomInfo',
        ),
        migrations.DeleteModel(
            name='RoomRecording',
        ),
        migrations.DeleteModel(
            name='RoomVisitors',
        ),
    ]
