# Generated by Django 3.1.4 on 2022-05-18 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0062_flashcard_is_required'),
        ('lesson_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonslacknotify',
            name='lesson_notify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses_api.lesson'),
        ),
    ]
