# Generated by Django 3.1.4 on 2022-05-18 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0063_delete_lessonemailnotify'),
        ('lesson_notifications', '0002_lessonslacknotify_lesson_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonemailnotify',
            name='lesson_notify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses_api.lesson'),
        ),
    ]
