# Generated by Django 3.1.4 on 2022-06-28 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0066_merge_20220615_1642'),
        ('lesson_notifications', '0003_lessonemailnotify_lesson_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonemailnotify',
            name='lesson_notify',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses_api.lesson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonslacknotify',
            name='lesson_notify',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses_api.lesson'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='lessonemailnotify',
            constraint=models.UniqueConstraint(fields=('lesson_notify', 'email'), name='uniqueEmailNotification'),
        ),
        migrations.AddConstraint(
            model_name='lessonslacknotify',
            constraint=models.UniqueConstraint(fields=('lesson_notify', 'url'), name='uniqueSlackNotification'),
        ),
    ]
