# Generated by Django 3.1.4 on 2021-01-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img_url', models.CharField(max_length=500)),
                ('room_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vistor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=2000)),
                ('email', models.EmailField(blank=True, max_length=512, null=True)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
            ],
        ),
    ]
