# Generated by Django 3.1.4 on 2021-02-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vconf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roominfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roomrecording',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roomvisitors',
            options={},
        ),
    ]
