# Generated by Django 3.1.4 on 2021-02-09 06:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vconf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_name', models.CharField(max_length=50, unique=True)),
                ('logo_url', models.TextField()),
                ('video_url', models.TextField()),
                ('slack_channel', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'profile_roominfo',
            },
        ),
        migrations.CreateModel(
            name='RoomVisitors',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vconf.roominfo')),
            ],
            options={
                'db_table': 'profile_roomvisitors',
            },
        ),
        migrations.CreateModel(
            name='RoomRecording',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recording_link', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vconf.roominfo')),
            ],
            options={
                'db_table': 'profile_roomrecording',
            },
        ),
    ]
