# Generated by Django 3.1.4 on 2021-02-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vconf', '0003_auto_20210209_1123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vistor',
            new_name='Visitor',
        ),
    ]
