# Generated by Django 3.1.4 on 2021-02-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vconf', '0004_auto_20210209_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='logo_img_url',
            new_name='logo_url',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='name',
            new_name='user_name',
        ),
    ]
