# Generated by Django 3.1.4 on 2021-02-10 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vconf', '0002_roominfo_roomrecording_roomvisitors'),
        ('vconf', '0005_auto_20210209_1129'),
    ]

    operations = [
    ]
