# Generated by Django 3.1.4 on 2021-02-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vconf', '0006_merge_20210210_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominfo',
            name='slack_channel',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='video_url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterModelTable(
            name='roominfo',
            table='roominfo',
        ),
        migrations.AlterModelTable(
            name='roomrecording',
            table='roomrecording',
        ),
        migrations.AlterModelTable(
            name='roomvisitors',
            table='roomvisitors',
        ),
    ]
