# Generated by Django 3.1.4 on 2021-02-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vconf', '0007_auto_20210211_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='room_name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
