# Generated by Django 3.1.4 on 2021-08-04 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vconf', '0010_categories'),
    ]

    operations = [
        #migrations.AlterModelTable(
        #   name='roominfo',
        #   table='roominfo',
        #),
        #migrations.AlterModelTable(
        #    name='roomrecording',
        #    table='roomrecording',
        #),
        #migrations.AlterModelTable(
        #    name='roomvisitors',
        #    table='roomvisitors',
        # ),
    ]
