# Generated by Django 3.1.4 on 2022-04-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vconf', '0012_auto_20210804_2023'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roominfo',
            table='roominfo',
        ),
        migrations.AlterModelTable(
            name='roomrecording',
            table='roomrecording',
        ),
        migrations.AlterModelTable(
            name='roomvisitors',
            table='roomvisitors',
        ),
    ]
