# Generated by Django 3.1.4 on 2022-06-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vconf', '0014_auto_20220504_2234'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roominfo',
            table='roominfo',
        ),
        migrations.AlterModelTable(
            name='roomrecording',
            table='roomrecording',
        ),
        migrations.AlterModelTable(
            name='roomvisitors',
            table='roomvisitors',
        ),
    ]
