# Generated by Django 3.1.4 on 2022-10-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vconf', '0016_auto_20220808_1955'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roominfo',
            table='roominfo',
        ),
        migrations.AlterModelTable(
            name='roomrecording',
            table='roomrecording',
        ),
        migrations.AlterModelTable(
            name='roomvisitors',
            table='roomvisitors',
        ),
    ]
