# Generated by Django 3.1.4 on 2022-09-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vconf', '0017_auto_20220919_1341'),
    ]

    operations = [
        # migrations.AlterModelTable(
        #     name='roominfo',
        #     table='roominfo',
        # ),
        # migrations.AlterModelTable(
        #     name='roomrecording',
        #     table='roomrecording',
        # ),
        # migrations.AlterModelTable(
        #     name='roomvisitors',
        #     table='roomvisitors',
        # ),
    ]
