# Generated by Django 3.1.4 on 2022-09-30 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vconf', '0018_auto_20220919_1356'),
    ]

    operations = [
    ]
