# Generated by Django 3.1.4 on 2022-10-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vconf', '0019_auto_20220930_1321'),
    ]

    operations = [
    ]
