# Generated by Django 3.1.4 on 2020-12-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('sign_data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
