# Generated by Django 3.1.4 on 2021-02-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbormade', '0002_neighborhood_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('capacity', models.IntegerField()),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
                ('teams', models.CharField(max_length=250)),
                ('sports', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
    ]
