# Generated by Django 3.1.4 on 2021-03-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbormade', '0003_stadium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_post_id', models.CharField(max_length=250)),
                ('title', models.TextField()),
                ('subreddit', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('score', models.CharField(max_length=100)),
                ('upvote_ratio', models.CharField(max_length=100)),
                ('num_comments', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
