# Generated by Django 3.1.4 on 2021-03-16 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbormade', '0005_auto_20210316_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subreddit',
            old_name='created',
            new_name='created_at',
        ),
    ]
