# Generated by Django 3.1.4 on 2021-03-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbormade', '0007_auto_20210317_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='reddit_post_id',
            field=models.CharField(max_length=250),
        ),
    ]
