# Generated by Django 2.2.8 on 2020-09-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbormade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='code_2fa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
