# Generated by Django 2.2.8 on 2020-09-07 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbormade', '0003_auto_20200907_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=256, null=True)),
                ('membership', models.CharField(blank=True, max_length=128, null=True)),
                ('payments', models.CharField(blank=True, max_length=128, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='neighbormadetoken',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbormade.Member')),
                ('memberstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbormade.MemberStore')),
            ],
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=256, null=True)),
                ('ordered_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbormade.Member')),
            ],
        ),
        migrations.AddField(
            model_name='memberstore',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbormade.Member'),
        ),
    ]
