# Generated by Django 2.2.8 on 2020-09-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbormade', '0004_auto_20200907_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
