# Generated by Django 2.2.8 on 2020-09-09 02:01

from django.db import migrations, models
import neighbormade.models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbormade', '0005_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberstore',
            name='business_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to=neighbormade.models.uuid_file_path),
        ),
    ]
