# Generated by Django 2.2.8 on 2020-09-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbormade', '0006_auto_20200909_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='photo1',
            field=models.URLField(blank=True, null=True),
        ),
    ]
