# Generated by Django 2.2.8 on 2020-10-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfapp2', '0002_auto_20201025_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='phone',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
