# Generated by Django 2.2.8 on 2020-10-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfapp2', '0003_auto_20201025_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='other_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='services',
            field=models.TextField(blank=True, null=True),
        ),
    ]
