# Generated by Django 2.2.8 on 2020-10-29 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfapp2', '0005_auto_20201026_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsCheckin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(default='', max_length=2000)),
                ('lat', models.CharField(default='', max_length=500)),
                ('lng', models.CharField(default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sfapp2.Member')),
            ],
        ),
    ]
