# Generated by Django 2.2.8 on 2020-11-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfapp2', '0008_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='question_answers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
