# Generated by Django 2.2.8 on 2020-11-11 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfapp2', '0009_member_question_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoUrl', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='', max_length=500)),
                ('member', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sfapp2.Member')),
            ],
        ),
    ]
