# Generated by Django 3.1.4 on 2021-01-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfapp2', '0011_videoupload_video_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_email', models.EmailField(blank=True, max_length=512, null=True)),
                ('member', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sfapp2.member')),
            ],
        ),
    ]
