# Generated by Django 2.2.8 on 2021-06-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfapp2', '0019_membergpsentry_membersession'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('phone',)},
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
    ]
