# Generated by Django 3.1.4 on 2022-10-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfapp2', '0022_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='position',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
