# Generated by Django 2.2.8 on 2020-12-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='braintreeID',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_payment',
            field=models.BooleanField(default=False),
        ),
    ]
