# Generated by Django 3.1.4 on 2022-09-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20220830_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='+910000000000', max_length=13, null=True),
        ),
    ]
