# Generated by Django 3.1.4 on 2022-09-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_remove_userprofile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.CharField(blank=True, default='Available', max_length=1000),
        ),
    ]
