# Generated by Django 3.1.4 on 2022-09-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20220919_1341'),
        ('profile', '0009_userprofile_about'),
    ]

    operations = [
    ]
