
from django.urls import path
from . import views

urlpatterns = [

    path("", views.apiOverview),
    path("lesson/create", views.lesson_create, name="lesson-create"),
    path("lesson/all", views.lesson_all, name="lesson-all"),
    path("lesson/read/<int:pk>", views.lesson_read, name="lesson-read"),
    path("lesson/update/<int:pk>/", views.lesson_update, name="lesson-update"),
    path("lesson/delete/<int:pk>/", views.lesson_delete, name="lesson-delete"),
    path("slide/read/<int:pk>", views.slide_read, name="slide-read"),
    path("flashcard/create/<str:lessonId>",
         views.flashcard_create, name="flashcard-create"),
    path("flashcard/read/<int:pk>/",
         views.flashcard_read, name="flashcard-read"),
    path("flashcard/update/<int:pk>/",
         views.flashcard_update, name="flashcard-update"),
    path("flashcard/delete/<int:pk>/",
         views.flashcard_delete, name="flashcard-delete"),
    path("flashcard/response",
         views.flashcard_response, name="flashcard-response"),

     path("session/create/<int:flashcardId>/",
          views.session_create, name="session-create"),
     path("session/list", views.session_list, name="session-list"),
     path("session/update/<int:flashcardId>/<int:pk>/",
          views.session_update, name="session-update"),
     path("session/get", views.get_user_session, name="get-user-session"),
     path("session/event/<str:flashcard_id>/<str:session_id>",
          views.user_session_event, name="session_event"),
     path("lesson/student/lesson-email-notify/<str:lessonId>",
          views.lesson_email_notify, name="lesson-email-notify"),
     path("lesson/student/lesson-email-notify-delete/<str:lessonId>",
          views.lesson_email_notify_delete, name="lesson-email-notify-delete"),
     path("lesson/student/get/mail/<str:lessonId>",
          views.email_responses, name="student-email-responses"),
     path("lesson/student/get/<str:student_id>",
          views.student_lesson_list, name="student-lesson-list"),
     path("lesson/response/get/<str:lesson_id>/<str:session_id>",
          views.lesson_flashcard_responses, name="get-lesson-response"),
     path("lesson/response/get/<str:lesson_id>/",
          views.overall_flashcard_responses, name="get-lesson-response"),
     path("user/response/get/<str:lesson_id>/",
          views.user_responses, name="get-lesson-response"),     
     path("confirm/phone", views.confirm_phone_number, name="confirm-phone-numer"),
     path("verify/phone", views.verify_2fa, name="verify-2fa"),
     path("verify/phone-verify",views.Phone_verification_check,name="phone_verfication_check"),
     path("invite/text",views.invite_text,name="invite-text"),
     path("invite/email",views.invite_email,name="invite-email"),
     path("invite/response", views.invite_response, name="invite-response"),
    path('code/get',views.get_2fa_code,
        name='get_2fa_code'),
]
