# Generated by Django 2.2.8 on 2020-12-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201211_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='braintreeID',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
