# Generated by Django 2.2.8 on 2020-12-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='postal_code',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
