# Generated by Django 2.2.8 on 2021-02-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210206_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='Company_name',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='first_name',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
