# Generated by Django 3.1.4 on 2021-02-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210215_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
