# Generated by Django 3.1.4 on 2021-03-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_item_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripeID',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripeSubscriptionID',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
