# Generated by Django 3.1.4 on 2021-02-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_item_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.TextField(default='', null=True),
        ),
    ]
