# Generated by Django 3.1.4 on 2021-03-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210314_1223'),
        ('store', '0016_braintreeconfig_user'),
    ]

    operations = [
    ]
