# Generated by Django 3.1.4 on 2021-03-16 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0017_merge_20210314_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('STRIPE_SECRET_KEY', models.CharField(max_length=70)),
                ('STRIPE_PUBLISHABLE_KEY', models.CharField(max_length=70)),
                ('STRIPE_LIVE_MODE', models.BooleanField(default=True)),
                ('STRIPE_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
