# Generated by Django 3.1.4 on 2021-03-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='source',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
