# Generated by Django 3.1.4 on 2021-04-19 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0020_subscription_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherUIMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=200)),
                ('delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('delivered_date', models.DateTimeField()),
                ('item_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
