# Generated by Django 3.1.4 on 2021-04-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_teacheruimessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheruimessage',
            name='delivered_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
