# Generated by Django 3.1.4 on 2021-04-23 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0024_auto_20210424_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacheruimessage',
            old_name='created_at',
            new_name='sent_at',
        ),
        migrations.RemoveField(
            model_name='teacheruimessage',
            name='receiver',
        ),
        migrations.AddField(
            model_name='teacheruimessage',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', related_query_name='r', to=settings.AUTH_USER_MODEL),
        ),
    ]
