# Generated by Django 3.1.4 on 2021-04-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20210424_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruimessage',
            name='conversation_id',
            field=models.CharField(default='44_45', max_length=200),
        ),
    ]
