# Generated by Django 3.1.4 on 2021-04-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_teacheruimessage_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheruimessage',
            name='conversation_id',
            field=models.CharField(max_length=200),
        ),
    ]
