# Generated by Django 3.1.4 on 2021-04-24 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20210424_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheruimessage',
            name='item_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
    ]
