# Generated by Django 3.1.4 on 2022-05-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20210424_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeconfig',
            name='STRIPE_PUBLISHABLE_KEY',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stripeconfig',
            name='STRIPE_SECRET_KEY',
            field=models.CharField(max_length=255),
        ),
    ]
