# Generated by Django 3.1.4 on 2022-06-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20220516_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_product_id', models.CharField(max_length=255)),
                ('stripe_price_id', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
