# Generated by Django 3.1.4 on 2022-06-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_stripeitem_flashcard_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeitem',
            name='flashcard_id',
        ),
    ]
