# Generated by Django 2.2.8 on 2020-11-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0003_auto_20201128_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='lesson_type',
            field=models.CharField(max_length=250),
        ),
    ]
