# Generated by Django 2.2.8 on 2020-11-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0004_auto_20201129_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='image',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
