# Generated by Django 2.2.8 on 2020-12-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0005_flashcard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
