# Generated by Django 2.2.8 on 2020-12-12 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0006_flashcard_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSessionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('user_device', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('view_duration', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('flash_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_api.FlashCard')),
            ],
        ),
    ]
