# Generated by Django 2.2.8 on 2020-12-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0007_usersessionevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersessionevent',
            name='view_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
