# Generated by Django 2.2.8 on 2020-12-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0008_auto_20201212_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersessionevent',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
