# Generated by Django 2.2.8 on 2020-12-12 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0009_auto_20201212_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersessionevent',
            name='end_time',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
