# Generated by Django 3.1.4 on 2020-12-22 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0010_auto_20201212_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCardResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250)),
                ('FlashCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_api.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_api.usersessionevent')),
            ],
        ),
    ]
