# Generated by Django 3.1.4 on 2020-12-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0012_auto_20201222_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardresponse',
            name='signature',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
