# Generated by Django 3.1.4 on 2020-12-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0013_auto_20201229_1804'),
        ('courses_api', '0013_flashcardresponse_signature'),
    ]

    operations = [
    ]
