# Generated by Django 3.1.4 on 2020-12-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0014_merge_20201229_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSession',
            new_name='UserLessonSession',
        ),
        migrations.RenameField(
            model_name='flashcardresponse',
            old_name='user_session',
            new_name='user_lesson_session',
        ),
    ]
