# Generated by Django 3.1.4 on 2020-12-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0015_auto_20201229_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardresponse',
            name='user_lesson_session',
        ),
        migrations.DeleteModel(
            name='UserLessonSession',
        ),
    ]
