# Generated by Django 3.1.4 on 2020-12-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0017_auto_20201229_1855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLessonSession',
            new_name='UserSession',
        ),
        migrations.RenameField(
            model_name='flashcardresponse',
            old_name='user_lesson_session',
            new_name='user_session',
        ),
    ]
