# Generated by Django 3.1.4 on 2020-12-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0020_auto_20201230_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
