# Generated by Django 3.1.4 on 2020-12-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0021_usersession_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='code_2fa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='has_verified_phone',
            field=models.BooleanField(default=False),
        ),
    ]
