# Generated by Django 3.1.4 on 2021-01-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0022_auto_20201230_0633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlashCardResponse',
        ),
    ]
