# Generated by Django 3.1.4 on 2021-01-02 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0023_delete_flashcardresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCardResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250)),
                ('signature', models.TextField(blank=True, default='', null=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_api.flashcard')),
                ('user_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses_api.usersession')),
            ],
        ),
    ]
