# Generated by Django 3.1.4 on 2021-01-02 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0024_flashcardresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardresponse',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses_api.lesson'),
        ),
    ]
