# Generated by Django 2.2.8 on 2021-01-26 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_braintreeconfig'),
        ('courses_api', '0025_flashcardresponse_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='braintree_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.BrainTreeConfig'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='item_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
    ]
