# Generated by Django 3.1.4 on 2021-01-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0025_flashcardresponse_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardresponse',
            name='signature',
        ),
    ]
