# Generated by Django 3.1.4 on 2021-02-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0029_auto_20210201_0517'),
        ('courses_api', '0029_auto_20210205_1601'),
    ]

    operations = [
    ]
