# Generated by Django 3.1.4 on 2021-02-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0032_invite_invite_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invite_type',
            field=models.CharField(max_length=10),
        ),
    ]
