# Generated by Django 3.1.4 on 2021-02-10 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0030_merge_20210209_0820'),
        ('courses_api', '0033_auto_20210209_0914'),
    ]

    operations = [
    ]
