# Generated by Django 3.1.4 on 2021-02-11 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_auto_20210205_0938'),
        ('courses_api', '0034_merge_20210210_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardresponse',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.student'),
        ),
    ]
