# Generated by Django 3.1.4 on 2021-02-16 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0030_merge_20210209_0920'),
        ('courses_api', '0035_flashcardresponse_student'),
    ]

    operations = [
    ]
