# Generated by Django 3.1.4 on 2021-02-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_auto_20210205_0938'),
        ('courses_api', '0036_merge_20210216_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_api.flashcard')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses_api.lesson')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.student')),
                ('user_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses_api.usersession')),
            ],
        ),
    ]
