# Generated by Django 3.1.4 on 2021-02-24 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0026_auto_20210126_1023'),
        ('courses_api', '0038_remove_inviteresponse_user_session'),
    ]

    operations = [
    ]
