# Generated by Django 3.1.4 on 2021-02-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0040_auto_20210225_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='answer',
        ),
    ]
