# Generated by Django 3.1.4 on 2021-02-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0043_remove_flashcard_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
