# Generated by Django 3.1.4 on 2021-03-11 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0044_flashcard_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='options',
        ),
    ]
