# Generated by Django 3.1.4 on 2021-03-11 01:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0045_remove_flashcard_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, null=True, size=None),
        ),
    ]
