# Generated by Django 3.1.4 on 2021-03-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0046_flashcard_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='meta_attributes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
