# Generated by Django 3.1.4 on 2021-04-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0047_lesson_meta_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_is_public',
            field=models.BooleanField(default=False),
        ),
    ]
