# Generated by Django 2.2.8 on 2021-05-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0048_lesson_lesson_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardresponse',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashcardresponse',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
