# Generated by Django 3.1.4 on 2021-05-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0049_auto_20210504_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardresponse',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashcardresponse',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
