# Generated by Django 3.1.4 on 2021-05-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0050_auto_20210511_0347'),
        ('courses_api', '0050_auto_20210509_0114'),
    ]

    operations = [
    ]
