# Generated by Django 2.2.8 on 2021-05-13 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0051_merge_20210512_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonEmailNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses_api.Lesson')),
            ],
        ),
    ]
