# Generated by Django 3.1.4 on 2021-05-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0052_lessonemailnotify'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='has_verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
