# Generated by Django 2.2.8 on 2021-05-31 05:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0054_auto_20210526_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), default=list, null=True, size=None),
        ),
    ]
