# Generated by Django 2.2.8 on 2021-06-01 11:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0055_auto_20210531_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='options',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
