# Generated by Django 2.2.8 on 2021-06-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0056_auto_20210601_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='longitude',
        ),
    ]
