# Generated by Django 3.1.4 on 2021-07-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0058_membergpsentry_membersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.CharField(max_length=2500),
        ),
    ]
