# Generated by Django 3.1.4 on 2021-07-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0059_auto_20210713_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardresponse',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
