# Generated by Django 3.1.4 on 2021-07-29 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0020_auto_20210722_2224'),
        ('courses_api', '0060_flashcardresponse_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.class'),
        ),
    ]
