# Generated by Django 3.1.4 on 2022-05-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0061_lesson__class'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='is_required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
