# Generated by Django 3.1.4 on 2022-05-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20210424_1403'),
        ('courses_api', '0062_flashcard_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='stripe_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.stripeconfig'),
        ),
    ]
