# Generated by Django 3.1.4 on 2022-05-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0063_flashcard_stripe_config'),
        ('courses_api', '0063_delete_lessonemailnotify'),
    ]

    operations = [
    ]
