# Generated by Django 3.1.4 on 2022-06-02 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20220602_1751'),
        ('courses_api', '0064_flashcard_stripe_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='stripe_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.stripeproductprice'),
        ),
    ]
