# Generated by Django 3.1.4 on 2022-06-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0064_merge_20220525_1818'),
        ('courses_api', '0065_auto_20220602_1751'),
    ]

    operations = [
    ]
