# Generated by Django 3.1.4 on 2022-08-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
