# Generated by Django 3.1.4 on 2022-08-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_member_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='meta_attributes',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
