# Generated by Django 3.1.4 on 2022-09-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20220830_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='member',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
