# Generated by Django 3.1.4 on 2022-09-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20220903_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='image',
            field=models.CharField(blank=True, default='https://www.iconfinder.com/icons/636895/users_avatar_group_human_people_profile_team_icon', max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
