# Generated by Django 3.1.4 on 2022-09-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20220909_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechannel',
            name='message_type',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
