# Generated by Django 3.1.4 on 2022-09-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_channel_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='about',
            field=models.CharField(blank=True, default='Please add discription about the channel', max_length=256, null=True),
        ),
    ]
