# Generated by Django 3.1.4 on 2022-09-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20220914_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='about',
        ),
    ]
