# Generated by Django 3.1.4 on 2022-09-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20220916_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmember',
            name='designation',
            field=models.CharField(choices=[('joined', 'joined'), ('leave', 'leave'), ('terminated', 'terminated')], default='joined', max_length=100),
        ),
    ]
