# Generated by Django 3.1.4 on 2022-09-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_auto_20220919_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmember',
            name='designation',
            field=models.CharField(choices=[('0', 'joined'), ('1', 'cancel'), ('2', 'leave'), ('3', 'requested'), ('-1', 'terminated')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='request_type',
            field=models.CharField(choices=[('0', 'joined'), ('1', 'cancel'), ('2', 'leave'), ('3', 'requested'), ('-1', 'terminated')], default='2', max_length=256),
        ),
    ]
