# Generated by Django 3.1.4 on 2022-09-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_auto_20220926_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='designation',
            field=models.CharField(choices=[('0', 'exist'), ('-2', 'arcade')], default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='channelmember',
            name='designation',
            field=models.CharField(choices=[('0', 'joined'), ('1', 'cancel'), ('2', 'leave'), ('3', 'requested'), ('-1', 'terminated'), ('-2', 'arcade')], default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='request_type',
            field=models.CharField(choices=[('0', 'joined'), ('1', 'cancel'), ('2', 'leave'), ('3', 'requested'), ('-1', 'terminated'), ('-2', 'arcade')], default='3', max_length=256),
        ),
    ]
