# Generated by Django 3.1.4 on 2022-09-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_auto_20220928_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='designation',
            new_name='isExist',
        ),
    ]
