# Generated by Django 3.1.4 on 2022-10-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_userlastseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageuser',
            name='message_staus',
            field=models.CharField(blank=True, default='unread', max_length=256, null=True),
        ),
    ]
