# Generated by Django 3.1.4 on 2022-10-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_messageuser_message_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageuser',
            old_name='message_staus',
            new_name='message_status',
        ),
    ]
