# Generated by Django 3.1.4 on 2022-10-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_groupuserlastseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='about',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='image',
            field=models.CharField(blank=True, default='https://www.iconfinder.com/icons/636895/users_avatar_group_human_people_profile_team_icon', max_length=500),
        ),
        migrations.AddField(
            model_name='org',
            name='phone_number',
            field=models.IntegerField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
