# Generated by Django 3.1.4 on 2021-01-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_class_classenrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
