# Generated by Django 3.1.4 on 2021-01-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_class_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='class_name',
        ),
    ]
