# Generated by Django 3.1.5 on 2021-01-27 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_classemailalert_classsmsalert_studentemailalert_studentsmsalert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classemailalert',
            old_name='class_entrolled',
            new_name='class_enrolled',
        ),
        migrations.RenameField(
            model_name='classsmsalert',
            old_name='class_entrolled',
            new_name='class_enrolled',
        ),
    ]
