# Generated by Django 3.1.4 on 2021-02-01 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_auto_20210127_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_id',
        ),
    ]
