# Generated by Django 3.1.4 on 2021-07-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_auto_20210616_0137'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='classenrolled',
            constraint=models.UniqueConstraint(fields=('student', 'class_enrolled'), name='Unique enrollment'),
        ),
    ]
