# Generated by Django 3.1.4 on 2021-08-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0020_auto_20210722_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
