# Generated by Django 2.2.8 on 2020-12-03 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('document_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('date', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=128)),
                ('listing_firm_commission', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('selling_firm_commission', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('refer_firm', models.CharField(max_length=640)),
                ('ref_broker_name', models.CharField(max_length=100)),
                ('refer_address', models.CharField(max_length=100)),
                ('refer_phone', models.CharField(max_length=17)),
                ('refer_email', models.CharField(max_length=30)),
                ('destination_firm', models.CharField(max_length=640)),
                ('dest_broker_name', models.CharField(max_length=100)),
                ('dest_address', models.CharField(max_length=100)),
                ('dest_phone', models.CharField(max_length=17)),
                ('dest_email', models.CharField(max_length=30)),
                ('is_seller', models.BooleanField(default=False)),
                ('is_buyer', models.BooleanField(default=False)),
                ('other', models.CharField(max_length=30)),
                ('pros_name', models.CharField(max_length=50)),
                ('pros_address', models.CharField(max_length=50)),
                ('pros_phone', models.CharField(max_length=50)),
                ('pros_email', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('months', models.IntegerField(default=18, validators=[django.core.validators.MaxValueValidator(30)])),
                ('ref_sign', models.TextField()),
                ('dest_sign', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
