# Generated by Django 2.2.8 on 2020-12-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_sign', '0003_auto_20201205_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
