# Generated by Django 2.2.8 on 2020-12-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_sign', '0004_auto_20201205_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='comments',
            field=models.TextField(default='', null=True),
        ),
    ]
