# Generated by Django 2.2.8 on 2020-12-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_sign', '0007_auto_20201205_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='dest_sign',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='ref_sign',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
