# Generated by Django 3.1.4 on 2021-02-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0003_auto_20210221_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
