# Generated by Django 3.1.4 on 2022-05-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_stripe', '0002_auto_20220516_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
