# Generated by Django 3.1.4 on 2022-05-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_stripe', '0003_auto_20220516_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stripe_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
