# Generated by Django 3.1.4 on 2022-05-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_stripe', '0006_auto_20220525_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='to_account',
            new_name='user',
        ),
    ]
