# Generated by Django 3.1.4 on 2022-06-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_stripe', '0007_auto_20220525_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripedetails',
            name='is_connected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
