


=================================1=================================================
#User
echo "from django.contrib.auth.models import User;from profile.models import UserProfile;user=User.objects.create_superuser('admin01@gmail.com','admin01@gmail.com','12345');userprofile=UserProfile.objects.update_or_create(user=user,);user=User.objects.create_superuser('admin02@gmail.com','admin02@gmail.com','12345');userprofile=UserProfile.objects.update_or_create(user=user,);user=User.objects.create_superuser('bran@gmail.com','bran@gmail.com','12345');userprofile=UserProfile.objects.update_or_create(user=user,);user=User.objects.create_superuser('sana@gmail.com','admin04@gmail.com','12345');userprofile=UserProfile.objects.update_or_create(user=user,);user=User.objects.create_superuser('arya@gmail.com','admin04@gmail.com','12345');userprofile=UserProfile.objects.update_or_create(user=user,);user=User.objects.create_superuser('rob@gmail.com','admin06@gmail.com','12345');userprofile=UserProfile.objects.update_or_create(user=user,);user=User.objects.create_superuser('john@gmail.com','admin06@gmail.com','12345');userprofile=UserProfile.objects.update_or_create(user=user,);user=User.objects.create_superuser('jaime@gmail.com','admin06@gmail.com','12345');userprofile=UserProfile.objects.update_or_create(user=user,);" | python3 manage.py shell
=================================2==========================================
#Org
echo "from chat.models import Org;from django.contrib.auth.models import User;Org.objects.create(user=User.objects.get(id = 1),meta_attributes='KV');Org.objects.create(user=User.objects.get(id = 2), meta_attributes='DPS')" | python3 manage.py shell


============================3==========================================
#Channel
echo "from django.contrib.auth.models import User;from chat.models import Org,Channel;Channel.objects.create(created_by=User.objects.get(id=1),name='class8',org=Org.objects.get(id=1));Channel.objects.create(created_by=User.objects.get(id=2),name='class9',org=Org.objects.get(id=1))" | python3 manage.py shell
=================================4====================================
# ChannelMember
echo "from django.contrib.auth.models import User;from profile.models import UserProfile;from chat.models import Org,Channel,ChannelMember,Member;ChannelMember.objects.create(Channel=Channel.objects.get(id=1),added_by=User.objects.get(id=1),user=User.objects.get(id=1),org=Org.objects.get(id=1));ChannelMember.objects.create(Channel=Channel.objects.get(id=1),added_by=User.objects.get(id=1),user=User.objects.get(id=2),org=Org.objects.get(id=1));ChannelMember.objects.create(Channel=Channel.objects.get(id=1),added_by=User.objects.get(id=1),user=User.objects.get(id=3),org=Org.objects.get(id=1));ChannelMember.objects.create(Channel=Channel.objects.get(id=1),added_by=User.objects.get(id=1),user=User.objects.get(id=4),org=Org.objects.get(id=1));ChannelMember.objects.create(Channel=Channel.objects.get(id=1),added_by=User.objects.get(id=1),user=User.objects.get(id=7),org=Org.objects.get(id=1));ChannelMember.objects.create(Channel=Channel.objects.get(id=2),added_by=User.objects.get(id=2),user=User.objects.get(id=1),org=Org.objects.get(id=1));ChannelMember.objects.create(Channel=Channel.objects.get(id=2),added_by=User.objects.get(id=2),user=User.objects.get(id=2),org=Org.objects.get(id=1));ChannelMember.objects.create(Channel=Channel.objects.get(id=2),added_by=User.objects.get(id=2),user=User.objects.get(id=5),org=Org.objects.get(id=1));ChannelMember.objects.create(Channel=Channel.objects.get(id=2),added_by=User.objects.get(id=2),user=User.objects.get(id=6),org=Org.objects.get(id=1));ChannelMember.objects.create(Channel=Channel.objects.get(id=2),added_by=User.objects.get(id=2),user=User.objects.get(id=8),org=Org.objects.get(id=1));" | python3 manage.py shell

=============================5===========================================
#Member

echo "from django.contrib.auth.models import User;from profile.models import UserProfile;from chat.models import Org,Member;Member.objects.create(user_profile=UserProfile.objects.get(id=1),user=User.objects.get(id=1),org=Org.objects.get(id=1));Member.objects.create(user_profile=UserProfile.objects.get(id=2),user=User.objects.get(id=2),org=Org.objects.get(id=1));Member.objects.create(user_profile=UserProfile.objects.get(id=3),user=User.objects.get(id=3),org=Org.objects.get(id=1));Member.objects.create(user_profile=UserProfile.objects.get(id=4),user=User.objects.get(id=4),org=Org.objects.get(id=1));Member.objects.create(user_profile=UserProfile.objects.get(id=5),user=User.objects.get(id=5),org=Org.objects.get(id=1));Member.objects.create(user_profile=UserProfile.objects.get(id=6),user=User.objects.get(id=6),org=Org.objects.get(id=1));Member.objects.create(user_profile=UserProfile.objects.get(id=7),user=User.objects.get(id=7),org=Org.objects.get(id=1));Member.objects.create(user_profile=UserProfile.objects.get(id=8),user=User.objects.get(id=8),org=Org.objects.get(id=1));" | python3 manage.py shell