# Generated by Django 3.1.4 on 2021-02-13 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0003_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('time_duration', models.IntegerField(default=0)),
                ('twilio_phone', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='voip.phone')),
            ],
        ),
    ]
