# Generated by Django 3.1.4 on 2021-02-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0005_admingroup_admingroupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
