# Generated by Django 3.1.4 on 2021-02-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0006_call_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_loist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_number', models.CharField(blank=True, max_length=20)),
                ('to_number', models.CharField(blank=True, max_length=20, null=True)),
                ('recording', models.FileField(max_length=500, upload_to=None)),
            ],
        ),
    ]
