# Generated by Django 3.1.4 on 2021-02-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0008_auto_20210224_0458'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='call_list',
            constraint=models.UniqueConstraint(fields=('date', 'from_number', 'to_number', 'recording'), name='unique appversion'),
        ),
        migrations.AlterModelTable(
            name='call_list',
            table='Call_list',
        ),
    ]
