# Generated by Django 3.1.4 on 2021-02-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0009_auto_20210224_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call_list',
            name='recording',
            field=models.CharField(max_length=500),
        ),
    ]
