# Generated by Django 3.1.4 on 2021-02-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0010_auto_20210224_0637'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='call_list',
            name='unique appversion',
        ),
        migrations.RemoveField(
            model_name='call_list',
            name='recording',
        ),
        migrations.AddField(
            model_name='call_list',
            name='duration',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='call_list',
            name='recording_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='call_list',
            name='from_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='call_list',
            name='to_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='call_list',
            constraint=models.UniqueConstraint(fields=('date', 'from_number', 'to_number', 'recording_url', 'duration'), name='unique appversion'),
        ),
    ]
