# Generated by Django 3.1.4 on 2021-03-10 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voip', '0012_auto_20210310_1100'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assigned_numbers',
            name='unique_assigned_number',
        ),
        migrations.AlterField(
            model_name='assigned_numbers',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='assigned_numbers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterModelTable(
            name='assigned_numbers',
            table=None,
        ),
    ]
