# Generated by Django 3.1.4 on 2021-03-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0014_auto_20210315_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
    ]
