# Generated by Django 3.1.4 on 2021-03-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0015_user_leads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_leads',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='user_leads',
            name='State',
        ),
        migrations.AddField(
            model_name='user_leads',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_leads',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_leads',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_leads',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
