# Generated by Django 3.1.4 on 2021-03-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0016_auto_20210317_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_leads',
            name='filter_lead',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
