# Generated by Django 3.1.4 on 2021-03-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0017_user_leads_filter_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_leads',
            name='filter_lead',
            field=models.CharField(blank=True, default='-', max_length=40, null=True),
        ),
    ]
