# Generated by Django 3.1.4 on 2021-03-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0018_auto_20210318_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_leads',
            name='filter_lead',
        ),
        migrations.AddField(
            model_name='user_leads',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user_leads',
            name='status',
            field=models.CharField(choices=[('1', '-'), ('2', 'Call back later'), ('3', 'not interested')], default='1', max_length=20),
        ),
    ]
