# Generated by Django 3.1.4 on 2021-03-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0020_auto_20210318_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_leads',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
