# Generated by Django 3.1.4 on 2021-03-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0021_auto_20210318_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_leads',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_leads',
            name='full_notes',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='user_leads',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
