# Generated by Django 3.1.4 on 2021-03-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0022_auto_20210319_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_leads',
            name='full_notes',
        ),
        migrations.AlterField(
            model_name='user_leads',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
