# Generated by Django 3.1.7 on 2021-03-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0023_delete_call_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_number', models.CharField(max_length=20, null=True)),
                ('to_number', models.CharField(max_length=20, null=True)),
                ('recording_url', models.CharField(max_length=500, null=True)),
                ('duration', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'Call_list',
            },
        ),
        migrations.AddConstraint(
            model_name='call_list',
            constraint=models.UniqueConstraint(fields=('date', 'from_number', 'to_number', 'recording_url', 'duration'), name='unique appversion'),
        ),
    ]
