# Generated by Django 3.1.4 on 2021-03-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0023_auto_20210322_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_leads',
            name='last_call',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_leads',
            name='recording_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
