# Generated by Django 3.1.4 on 2021-03-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0026_auto_20210325_1237'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user_leads',
            name='uniqueUserLead',
        ),
        migrations.AddConstraint(
            model_name='user_leads',
            constraint=models.UniqueConstraint(fields=('name', 'phone', 'email', 'price', 'state', 'url', 'notes'), name='uniqueUserLead'),
        ),
    ]
