# Generated by Django 3.1.7 on 2021-03-31 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0027_auto_20210325_1244'),
        ('voip', '0024_auto_20210326_0722'),
    ]

    operations = [
    ]
