# Generated by Django 3.1.7 on 2021-03-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0028_merge_20210331_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Call_list',
            new_name='CallList',
        ),
        migrations.AlterModelTable(
            name='calllist',
            table='CallList',
        ),
    ]
