# Generated by Django 3.1.7 on 2021-04-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0029_auto_20210331_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllist',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
