# Generated by Django 3.1.4 on 2021-04-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0030_auto_20210402_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllist',
            name='date',
            field=models.DateField(),
        ),
    ]
