# Generated by Django 3.1.7 on 2021-04-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0031_auto_20210407_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllist',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
