# Generated by Django 3.1.4 on 2021-04-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0032_auto_20210407_0516'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user_leads',
            name='uniqueUserLead',
        ),
        migrations.RenameField(
            model_name='user_leads',
            old_name='price',
            new_name='ask',
        ),
        migrations.AddConstraint(
            model_name='user_leads',
            constraint=models.UniqueConstraint(fields=('name', 'phone', 'email', 'ask', 'state', 'url', 'notes'), name='uniqueUserLead'),
        ),
    ]
