# Generated by Django 3.1.4 on 2021-05-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0034_merge_20210509_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllist',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
