# Generated by Django 2.2.8 on 2021-05-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0036_auto_20210525_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_leads',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_leads',
            name='ask',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_leads',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_leads',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_leads',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_leads',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_leads',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_leads',
            name='status',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='user_leads',
            name='zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
