# Generated by Django 3.1.4 on 2021-07-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0037_auto_20210525_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(blank=True, max_length=20, null=True)),
                ('to_number', models.CharField(blank=True, max_length=20, null=True)),
                ('msg_body', models.CharField(blank=True, max_length=500, null=True)),
                ('direction', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
