# Generated by Django 3.1.4 on 2021-07-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0038_sms_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_details',
            name='msg_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
