# Generated by Django 3.1.4 on 2021-07-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0039_auto_20210714_1301'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calllist',
            name='unique appversion',
        ),
        migrations.AddField(
            model_name='calllist',
            name='direction',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='calllist',
            constraint=models.UniqueConstraint(fields=('date', 'from_number', 'to_number', 'recording_url', 'duration', 'direction'), name='unique appversion'),
        ),
    ]
