# Generated by Django 3.1.4 on 2022-05-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0040_auto_20210723_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_leads',
            name='contact_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_leads',
            name='tax_overdue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
