# Generated by Django 3.1.4 on 2022-05-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0041_auto_20220503_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_leads',
            name='last_dial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
