# Generated by Django 3.1.4 on 2022-05-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0042_user_leads_last_dial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('dest_number', models.CharField(blank=True, max_length=40, null=True)),
                ('callsid', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
