# Generated by Django 3.1.4 on 2022-05-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0043_twiliosession'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliosession',
            name='confsid',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
