# Generated by Django 3.1.4 on 2022-05-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0045_sms_details_sid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user_leads',
            name='uniqueUserLead',
        ),
        migrations.RenameField(
            model_name='user_leads',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user_leads',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='user_leads',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'phone', 'email', 'ask', 'state', 'url', 'notes'), name='uniqueUserLead'),
        ),
    ]
