# Generated by Django 3.1.4 on 2022-06-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0046_auto_20220523_0903'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calllist',
            name='unique appversion',
        ),
        migrations.AddField(
            model_name='calllist',
            name='sid',
            field=models.CharField(max_length=34, null=True, unique=True),
        ),
    ]
