# Generated by Django 3.1.4 on 2022-06-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0048_auto_20220608_2124'),
        ('voip', '0048_auto_20220610_1651'),
    ]

    operations = [
    ]
