# Generated by Django 3.1.4 on 2022-06-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSIDReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('channel', models.CharField(blank=True, max_length=512, null=True)),
                ('frequency', models.CharField(blank=True, max_length=512, null=True)),
                ('quality', models.CharField(blank=True, max_length=512, null=True)),
                ('signal_level', models.CharField(blank=True, max_length=512, null=True)),
                ('encryption_key', models.CharField(blank=True, max_length=512, null=True)),
                ('essID', models.CharField(blank=True, max_length=512, null=True)),
                ('bit_rates', models.CharField(blank=True, max_length=512, null=True)),
                ('mode', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
