<<<<<<< HEAD
# Generated by Django 3.1.4 on 2022-06-08 06:08
=======
# Generated by Django 3.1.4 on 2022-06-10 16:45
>>>>>>> 23140e5566e204f9a6cc34c1c8843b33c16176be

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSIDReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=512)),
                ('channel', models.CharField(max_length=512)),
                ('quality', models.CharField(max_length=512)),
                ('building_floor', models.IntegerField(max_length=512)),
                ('quality_int', models.IntegerField(max_length=512)),
=======
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('channel', models.CharField(blank=True, max_length=512, null=True)),
                ('frequency', models.CharField(blank=True, max_length=512, null=True)),
                ('quality', models.CharField(blank=True, max_length=512, null=True)),
                ('signal_level', models.CharField(blank=True, max_length=512, null=True)),
                ('encryption_key', models.CharField(blank=True, max_length=512, null=True)),
                ('essID', models.CharField(blank=True, max_length=512, null=True)),
                ('bit_rates', models.CharField(blank=True, max_length=512, null=True)),
                ('mode', models.CharField(blank=True, max_length=512, null=True)),
>>>>>>> 23140e5566e204f9a6cc34c1c8843b33c16176be
            ],
        ),
    ]
