# Generated by Django 2.2.20 on 2022-06-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0003_ssidreading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssidreading',
            name='building_floor',
        ),
        migrations.RemoveField(
            model_name='ssidreading',
            name='quality_int',
        ),
        migrations.RemoveField(
            model_name='ssidreading',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='ssidreading',
            name='bit_rates',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='ssidreading',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='ssidreading',
            name='essID',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='ssidreading',
            name='frequency',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='ssidreading',
            name='mode',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='ssidreading',
            name='signal_level',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='ssidreading',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='ssidreading',
            name='channel',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='ssidreading',
            name='quality',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
